version: "3"

services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /workspace
        command: sleep infinity
        volumes:
            - ./:/workspace
