name: create PR by github-actions[bot]
on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        required: true
      reviewer:
        type: string
        required: true    
      gh_token:
        type: string
        required: true
    outputs:
      pr_id:
        description: "作成したプルリクエストのID"
        value: ${{ jobs.create_pr.steps.get_pr.outputs.pr_id }}
jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ inputs.gh_token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B ${{ inputs.base_branch }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: |
          gh pr create --fill -B ${{ inputs.base_branch }} -r ${{ inputs.reviewer }}    
      - id: get_pr
        name: Get PR
        run: |
          echo "count=$(gh pr list -B ${{ inputs.base_branch }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
          echo "pr_id=$(gh pr list -B ${{ inputs.base_branch }} -H ${{ github.ref_name }} --json 'number' -q '.[].number')" >> $GITHUB_OUTPUT