name: create PR by github-actions[bot]
on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - closed
env:
  BASE_BRANCH: ${{ github.ref == 'refs/heads/main' ? 'main': 'develop' }}
  REVIEWER: YutaCurry
jobs:
  tf_apply:
    uses: ./.github/workflows/_tf_apply.yml
    with:
      TF_WORK_DIR: bin/main
      BASE_BRANCH: ${{ env.BASE_BRANCH }}
    secrets: inherit