name: create PR by github-actions[bot]
on:
  push:
    branches:
      - '**/dev/**'
env:
  BASE_BRANCH: develop
  REVIEWER: YutaCurry
  GH_TOKEN: ${{ github.token }}
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: |
          gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}    
      - id: get_pr
        name: Get PR
        run: |
          echo "pr_id=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'number' -q '.[].number')" >> $GITHUB_OUTPUT
    outputs:
      pr_count: ${{ steps.check_pr.outputs.count }}
      pr_id: ${{ steps.get_pr.outputs.pr_id }}
      base_branch: ${{ env.BASE_BRANCH }}
  write_plan_pr:
    needs: create_pr
    if: ${{ needs.create_pr.outputs.pr_count != '' }}
    uses: ./.github/workflows/_tf_plan.yml
    with:
      TF_WORK_DIR: bin/main
      BASE_BRANCH: ${{ needs.create_pr.outputs.base_branch }}
      PR_ID: ${{ needs.create_pr.outputs.pr_id }}
    secrets: inherit