name: create PR by github-actions[bot]
on:
  push:
    branches:
      - '**/dev/**'
env:
  BASE_BRANCH: develop
  REVIEWER: YutaCurry
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_pr:
    # ブランチが作成されただけならスキップ
    # if: ${{ !github.event.created }}
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3
        with:
          # PRのタイトルとかをコミット履歴から取得するので、
          # fetch-depthを0に設定して全履歴を取得
          fetch-depth: 0

      # PRがすでに存在していないかのチェック
      # gh pr listでbase/headのブランチが同じPR検索して判定
      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
      # PRがまだなかったらghコマンドで生成
      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}
  write_plan_pr:
    uses: ./.github/workflows/_tf_plan.yml
    with:
      TF_WORK_DIR: bin/main
      PR_ID: 1
      BASE_BRANCH: develop
    secrets: inherit
    needs: create_pr


      # pull requestにterrafrom planの内容を載せる